# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: list all tasks
    cmds:
      - task --list-all
    silent: true
  setup:
    desc: setup dependencies
    cmds:
      - npm i
  start:
    desc: start in development mode
    cmds:
      - task setup
      - npm run dev
  start-prod:
    desc: start in producion mode
    cmds:
      - task setup
      - npm start
